### ISSUE TITLE
Double Beds purchased from custom shops display textures weirdly

### ISSUE THREAD

**Issue by Asterisk555** [Floogen/AlternativeTextures#44]
Double Beds purchased from [custom shops](https://www.nexusmods.com/stardewvalley/mods/13078) display textures weirdly. Beds purchased from robin, spawned through CJB, or the furniture catalogue are fine. All other furniture seem to be fine, including beds and child beds.

[smapi log](https://smapi.io/log/b29dc95b46a9434eabec558b42b1b145) from when I tested it
[smapi log](https://smapi.io/log/a4d321b0a32444cea4110855a60de568) from when Erin first reported the issue

[double bed thinks it's a single](https://postimg.cc/QBbCLbGH)
[if you retexture it then it turns into a shadow](https://postimg.cc/JsxD9rQm)
[or bands of colour](https://postimg.cc/Wh6hkNCr/234cae26)

I tried changing how I was listing the item with shop tile framework but the issue persisted

**Comment by Floogen** [comment]
This issue seems to occur regardless regardless if Alternative Textures is installed or not, so I don't believe this is a bug with AT. Since it only seems to occur when using an STF shop, I would assume it is something on that framework's side.

![image](https://user-images.githubusercontent.com/31755155/182004130-54b6dbff-601b-48b2-a994-5f5782f58bd8.png)
